<?php
// auto-generated by Goteo\Application\Config\YamlSettingsLoader
// date: 2019/08/01 16:05:25
return array (
  'secret' => '--a-very-secret-string---',
  'env' => 'real',
  'debug' => true,
  'lang' => 'es',
  'url' => 
  array (
    'main' => '//0.0.0.0:8081',
  ),
  'plugins' => 
  array (
    'goteo-dev' => 
    array (
      'active' => true,
      'mocks' => NULL,
    ),
  ),
  'payments' => 
  array (
    'paypal' => 
    array (
      'active' => true,
      'testMode' => true,
      'username' => 'paypal@example.com',
      'password' => 'paypal-password',
      'signature' => 'PAYPAL-Signature',
      'appId' => 'PAYPAL-APP-ID',
    ),
    'dummy' => 
    array (
      'active' => true,
    ),
  ),
  'db' => 
  array (
    'driver' => 'mysql',
    'host' => 'mariadb',
    'port' => 3306,
    'charset' => 'utf8mb4',
    'database' => 'goteo',
    'username' => 'goteo',
    'password' => 'goteo',
  ),
  'meta' => 
  array (
    'title' => 'Development Goteo',
  ),
  'mail' => 
  array (
    'mail' => 'info@goteo.test',
    'contact' => 'info@goteo.test',
    'manager' => 'manager@goteo.test',
    'fail' => 'dev@goteo.test',
    'log' => 'sitelog@goteo.test',
    'transport' => 
    array (
      'from' => 'noreply@goteo.test',
      'name' => 'Goteo Test',
      'type' => 'smtp',
      'smtp' => 
      array (
        'auth' => false,
        'secure' => false,
        'host' => 'mailhog',
        'port' => 1025,
      ),
    ),
  ),
  'geolocation' => 
  array (
    'maxmind' => 
    array (
      'cities' => '/usr/share/GeoIP/GeoLite2-City.mmdb',
    ),
    'google_maps_key' => NULL,
  ),
  'oauth' => 
  array (
    'facebook' => 
    array (
      'active' => false,
      'id' => 0,
      'secret' => 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    ),
    'twitter' => 
    array (
      'active' => false,
      'id' => 'aaaaaaaaaaaaaaaaaaaaaa',
      'secret' => 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    ),
    'linkedin' => 
    array (
      'active' => false,
      'id' => 'aaaaaaaaaaaa',
      'secret' => 'aaaaaaaaaaaaaaaa',
    ),
    'google' => 
    array (
      'active' => false,
      'id' => 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      'secret' => 'aaaaaaaaaaaaaaaaaa',
    ),
  ),
  'analytics' => 
  array (
    'google' => NULL,
  ),
);
