<?php
// auto-generated by Goteo\Application\Config\YamlSettingsLoader
// date: 2019/08/01 18:05:26
return array (
  'en' => 
  array (
    'name' => 'English',
    'short' => 'ENG',
    'public' => true,
    'locale' => 'en_GB',
    'fallback' => 'es',
  ),
  'es' => 
  array (
    'name' => 'Español',
    'short' => 'ES',
    'public' => true,
    'locale' => 'es_ES',
    'fallback' => 'en',
  ),
  'ca' => 
  array (
    'name' => 'Català',
    'short' => 'CAT',
    'public' => true,
    'locale' => 'ca_ES',
    'fallback' => 'es',
  ),
  'eu' => 
  array (
    'name' => 'Euskara',
    'short' => 'EUSK',
    'public' => true,
    'locale' => 'eu_ES',
    'fallback' => 'es',
  ),
  'gl' => 
  array (
    'name' => 'Galego',
    'short' => 'GAL',
    'public' => true,
    'locale' => 'gl_ES',
    'fallback' => 'es',
  ),
  'ast' => 
  array (
    'name' => 'Asturiano',
    'short' => 'AST',
    'public' => true,
    'locale' => 'as_ES',
    'fallback' => 'es',
  ),
  'fr' => 
  array (
    'name' => 'Français',
    'short' => 'FRA',
    'public' => true,
    'locale' => 'fr_FR',
    'fallback' => 'en',
  ),
  'it' => 
  array (
    'name' => 'Italiano',
    'short' => 'ITA',
    'public' => true,
    'locale' => 'it_IT',
    'fallback' => 'en',
  ),
  'he' => 
  array (
    'name' => 'עברית',
    'short' => 'HEB',
    'public' => false,
    'locale' => 'he_IL',
    'fallback' => 'en',
  ),
  'nl' => 
  array (
    'name' => 'Dutch',
    'short' => 'NL',
    'public' => true,
    'locale' => 'nl_NL',
    'fallback' => 'en',
  ),
  'de' => 
  array (
    'name' => 'Deutsch',
    'short' => 'DE',
    'public' => true,
    'locale' => 'de_DE',
    'fallback' => 'en',
  ),
  'el' => 
  array (
    'name' => 'Ελληνικά',
    'short' => 'GRK',
    'public' => false,
    'locale' => 'el_GR',
    'fallback' => 'en',
  ),
  'pl' => 
  array (
    'name' => 'Polski',
    'short' => 'POL',
    'public' => false,
    'locale' => 'pl_PL',
    'fallback' => 'en',
  ),
  'pt' => 
  array (
    'name' => 'Português',
    'short' => 'PORT',
    'public' => false,
    'locale' => 'pt_PT',
    'fallback' => 'en',
  ),
  'ar' => 
  array (
    'name' => 'العربية',
    'short' => 'AR',
    'public' => false,
    'locale' => 'ar_MA',
    'fallback' => 'en',
  ),
  'tr' => 
  array (
    'name' => 'Türkçe',
    'short' => 'TUR',
    'public' => false,
    'locale' => 'tr_TR',
    'fallback' => 'en',
  ),
  'sv' => 
  array (
    'name' => 'Svenska',
    'short' => 'SV',
    'public' => true,
    'locale' => 'sv_SE',
    'fallback' => 'en',
  ),
  'fil' => 
  array (
    'name' => 'Filipino',
    'short' => 'FIL',
    'public' => false,
    'locale' => 'fil',
    'fallback' => 'en',
  ),
  'id' => 
  array (
    'name' => 'Bahasa Indonesia',
    'short' => 'IND',
    'public' => false,
    'locale' => 'id_ID',
    'fallback' => 'en',
  ),
  'ja' => 
  array (
    'name' => '日本語',
    'short' => 'JPN',
    'public' => false,
    'locale' => 'ja_JP',
    'fallback' => 'en',
  ),
  'ro' => 
  array (
    'name' => 'Română',
    'short' => 'RUM',
    'public' => false,
    'locale' => 'ro_RO',
    'fallback' => 'en',
  ),
);
