<?php
// auto-generated by Goteo\Application\Config\YamlSettingsLoader
// date: 2019/08/01 18:05:26
return array (
  'EUR' => 
  array (
    'name' => 'Euro',
    'symbol' => '€',
    'thousands' => '.',
    'decimal' => ',',
    'active' => true,
  ),
  'USD' => 
  array (
    'name' => 'U.S. Dollar',
    'symbol' => '$',
    'thousands' => ',',
    'decimal' => '.',
    'active' => true,
  ),
  'GBP' => 
  array (
    'name' => 'British Pound',
    'symbol' => '£',
    'thousands' => ',',
    'decimal' => '.',
    'active' => true,
  ),
);
