<?php
// auto-generated by Goteo\Application\Config\YamlSettingsLoader
// date: 2019/08/01 18:05:26
return array (
  'user' => 
  array (
    'perms' => 
    array (
      0 => 'create-project',
      1 => 'edit-project',
      2 => 'remove-project',
    ),
    'level' => 0,
  ),
  'vip' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'recommend-projects',
    ),
    'level' => 10,
  ),
  'translator' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'translate-language',
      1 => 'full-html-edit',
    ),
    'level' => 20,
  ),
  'caller' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'create-call',
      1 => 'edit-call',
      2 => 'remove-call',
    ),
    'level' => 30,
  ),
  'checker' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'review-project',
    ),
    'level' => 40,
  ),
  'blogger' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'admin-module-blog',
      1 => 'full-html-edit',
    ),
    'level' => 40,
  ),
  'stats' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'admin-module-stats',
    ),
    'level' => 40,
  ),
  'manager' => 
  array (
    'extends' => 'user',
    'perms' => 
    array (
      0 => 'view-any-project',
      1 => 'edit-published-projects',
      2 => 'view-any-call',
      3 => 'edit-published-calls',
      4 => 'admin-module-blog',
      5 => 'admin-module-stories',
      6 => 'full-html-edit',
      7 => 'admin-module-stats',
    ),
    'level' => 50,
  ),
  'consultant' => 
  array (
    'extends' => 'checker',
    'perms' => 
    array (
      0 => 'view-any-project',
      1 => 'publish-projects',
      2 => 'edit-projects',
      3 => 'remove-projects',
      4 => 'view-any-call',
      5 => 'publish-calls',
      6 => 'edit-calls',
      7 => 'remove-calls',
      8 => 'impersonate-owners',
      9 => 'assign-checker',
      10 => 'admin-module-users',
      11 => 'admin-module-blog',
      12 => 'admin-module-stories',
      13 => 'admin-module-stats',
      14 => 'admin-module-promote',
      15 => 'full-html-edit',
    ),
    'level' => 60,
  ),
  'admin' => 
  array (
    'extends' => 'consultant',
    'perms' => 
    array (
      0 => 'assign-consultant',
      1 => 'publish-any-project',
      2 => 'edit-any-project',
      3 => 'remove-any-project',
      4 => 'publish-any-call',
      5 => 'edit-any-call',
      6 => 'remove-any-call',
      7 => 'rebase-users',
      8 => 'impersonate-users',
      9 => 'admin-module-categories',
    ),
    'level' => 70,
  ),
  'superadmin' => 
  array (
    'extends' => 'admin',
    'perms' => 
    array (
      0 => 'admin-any-module',
    ),
    'level' => 80,
  ),
  'root' => 
  array (
    'extends' => 'superadmin',
    'perms' => 
    array (
      0 => 'impersonate-everyone',
    ),
    'level' => 90,
  ),
);
