<?php
// auto-generated by Goteo\Application\Config\YamlSettingsLoader
// date: 2019/08/01 16:05:25
return array (
  'maintenance' => false,
  'autosave' => true,
  'session' => 
  array (
    'time' => 3600,
    'skip' => 
    array (
      0 => '/invest/notify/',
      1 => '/img/',
    ),
  ),
  'env' => 'real',
  'debug' => false,
  'node' => 'goteo',
  'lang' => 'es',
  'sql_lang' => 'es',
  'timezone' => 'Europe/Madrid',
  'currency' => 'EUR',
  'ssl' => false,
  'proxies' => 
  array (
    0 => '127.0.0.1',
  ),
  'url' => 
  array (
    'redirect' => 
    array (
      'skip' => 
      array (
        0 => '/password-recovery',
        1 => '/api',
      ),
      'fixed' => 
      array (
        0 => '/login',
        1 => '/password-reset',
        2 => '/signup',
      ),
    ),
  ),
  'plugins' => 
  array (
    'goteo-dev' => 
    array (
      'active' => false,
    ),
    'plugin-responsive' => 
    array (
      'active' => false,
    ),
    'invest-return' => 
    array (
      'active' => false,
    ),
    'custom-domains' => 
    array (
      'active' => false,
      'domains' => NULL,
      'redirects' => NULL,
    ),
    'private-zones' => 
    array (
      'active' => false,
    ),
  ),
  'payments' => 
  array (
    'paypal' => 
    array (
      'active' => false,
      'testMode' => true,
      'username' => 'paypal@example.com',
      'password' => 'paypal-password',
      'signature' => 'PAYPAL-Signature',
      'appId' => 'PAYPAL-APP-ID',
      'commissions' => 
      array (
        'refunded' => 
        array (
          'fixed' => 0.35,
          'percent' => 0,
        ),
        'charged' => 
        array (
          'fixed' => 0.35,
          'percent' => 3.4,
        ),
      ),
    ),
    'pool' => 
    array (
      'active' => true,
      'commissions' => 
      array (
        'refunded' => 
        array (
          'fixed' => 0,
          'percent' => 0,
        ),
        'charged' => 
        array (
          'fixed' => 0,
          'percent' => 0,
        ),
      ),
    ),
    'dummy' => 
    array (
      'active' => false,
    ),
  ),
  'db' => 
  array (
    'driver' => 'mysql',
    'host' => 'localhost',
    'port' => 3306,
    'charset' => 'utf8mb4',
    'database' => 'goteo',
    'username' => 'goteo',
    'password' => 'password',
    'cache' => 
    array (
      'driver' => NULL,
      'time' => 5,
      'long_time' => 3600,
    ),
    'replica' => 
    array (
      'host' => NULL,
      'port' => 3306,
      'username' => 'db-replica-username',
      'password' => 'db-replica-password',
    ),
  ),
  'meta' => 
  array (
    'title' => '--meta-title--',
    'description' => '--meta-description--',
    'keywords' => '--keywords--',
    'author' => '--author--',
    'copyright' => '--copyright--',
  ),
  'fee' => 4,
  'vat' => 10.5,
  'filesystem' => 
  array (
    'handler' => 'local',
    'aws' => 
    array (
      'key' => 'your-aws-key',
      'secret' => 'your-aws-secret',
      'region' => 'eu-west-1',
    ),
    'bucket' => 
    array (
      'static' => 'static.example.com',
      'mail' => 'mail-archive.example.com',
    ),
  ),
  'mail' => 
  array (
    'mail' => 'info@example.com',
    'contact' => 'info@example.com',
    'manager' => 'manager@example.com',
    'fail' => 'dev@example.com',
    'log' => 'sitelog@example.com',
    'beta_senders' => '(.+)example\\.org|(.+)example\\.com',
    'bcc_verifier' => NULL,
    'consultants' => NULL,
    'transport' => 
    array (
      'from' => 'noreply@example.com',
      'name' => 'Goteo Sender',
      'type' => 'smtp',
      'smtp' => 
      array (
        'auth' => true,
        'secure' => 'ssl',
        'host' => 'smtp.example.com',
        'port' => 587,
        'username' => 'smtp-usermail',
        'password' => 'smtp-password',
      ),
    ),
    'quota' => 
    array (
      'total' => 50000,
      'sender' => 40000,
      'send_rate' => 10,
      'concurrency' => 10,
    ),
    'sns' => 
    array (
      'client_id' => 'XXXXXXXXX',
      'region' => 'us-east-1',
      'bounces_topic' => 'amazon-ses-bounces',
      'complaints_topic' => 'amazon-ses-complaints',
    ),
  ),
  'geolocation' => 
  array (
    'google_maps_key' => NULL,
  ),
  'log' => 
  array (
    'app' => 'info',
    'payment' => 'debug',
    'console' => 'debug',
    'mail' => 'critical',
  ),
  'oauth' => 
  array (
    'facebook' => 
    array (
      'active' => false,
      'id' => NULL,
      'secret' => NULL,
    ),
    'twitter' => 
    array (
      'active' => false,
      'id' => NULL,
      'secret' => NULL,
    ),
    'linkedin' => 
    array (
      'active' => false,
      'id' => NULL,
      'secret' => NULL,
    ),
    'google' => 
    array (
      'active' => false,
      'id' => NULL,
      'secret' => NULL,
    ),
    'yahoo' => 
    array (
      'active' => false,
    ),
    'openid' => 
    array (
      'active' => true,
    ),
  ),
  'analytics' => 
  array (
    'google' => NULL,
    'matomo' => 
    array (
      'id' => NULL,
      'url' => '//xxx.matomo.cloud',
    ),
  ),
  'rewards' => 
  array (
    'required' => 3,
  ),
  'blog' => 
  array (
    'sections' => 
    array (
      'mission' => 'blog-section-mission',
      'matchfunding' => 'blog-section-matchfunding',
      'voices' => 'blog-section-voices',
      'transparency' => 'blog-section-transparency',
      'milestones' => 'blog-section-milestones',
      'team' => 'blog-section-team',
    ),
  ),
  'stories' => 
  array (
    'types' => 
    array (
      'pitcher' => 'stories-type-pitcher',
      'matcher' => 'stories-type-matcher',
    ),
  ),
  'donate' => 
  array (
    'landing' => false,
    'dashboard' => false,
    'tip' => false,
  ),
);
